version: '3.3'
services:
  gotify:
    ports:
      - 8080:80
    image: gotify/server
    container_name: gotify
    volumes:
      - /home/docker/gotify:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - TZ=Asia/Bangkok
networks:
  proxy:
    external: true